# Generated by Django 4.2.3 on 2023-07-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication',
            field=models.DateField(auto_now_add=True),
        ),
    ]
