# Generated by Django 4.2.3 on 2023-07-11 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('copies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lending_date', models.DateField(auto_now_add=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('avaliable', models.BooleanField(default=True)),
                ('lock_time', models.IntegerField(default=0)),
                ('copies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lendings', to='copies.copies')),
            ],
        ),
    ]
