# Generated by Django 4.2.3 on 2023-07-04 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lending', '0002_alter_lending_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lending',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lendings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
