# Generated by Django 4.2.3 on 2023-07-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lending',
            name='avaliable',
            field=models.BooleanField(default=True),
        ),
    ]
